### ISSUE TITLE
Use LOVD APIs instead of web scraping

### ISSUE THREAD

**Issue by ifokkema** [ErasmusMC-Bioinformatics/molclass#1]
Instead of [web scraping](https://github.com/ErasmusMC-Bioinformatics/molclass/blob/master/sources/lovd.py), please use the [LOVD APIs](https://www.lovd.nl/3.0/docs/manual.html#pf4b). Not only will you be able to retrieve results regardless of the transcript used, but you'll also just receive JSON data instead of HTML that you then need to parse. From a quick glance at your code, you'll be able to retrieve all the data you need from the APIs. Sharing more may be a copyright infringement anyway, depending on your setup. Send me an email at Ivo@[LOVD website]; I'll gladly provide some additional info together with the manual that I linked to above, so you can get started using the APIs.

**Comment by davidvanzessen** [comment]
Hi,

So sorry about this, with the number of sources Molclass is using I didn't spend a lot of time checking if there were APIs available for all of them.

I will switch the LOVD source over to the API as soon as possible.
